theme: minima
title: A Padawan Programmer's Passage to Proficiency
author: Beth Wakefield
email: bethmwakefield@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 The key to pursuing excellence is to embrace an organic, long-term learning process, and not to live in a shell of static, safe mediocrity. Usually, growth comes at the expense of previous comfort or safety."
— Josh Waitzkin

# social links
github_username:  bethwakefield

show_excerpts: true # set to false to remove excerpts on the homepage
